### PR TITLE
PhoneGap Developer App 1.7.2 release post

### PR DESCRIPTION
**Pull request by timkim**

### CODE REVIEW

**Comment by mwbrooks** [comment]
Nice @timkim! Work in progress by the looks of it?

**Comment by timkim** [comment]
Tis more fleshed out now. I think that should be good now.

**Comment by GarthDB** [comment]
do you want a content review @timkim ? Would you want to do it @mwbrooks ?

**Comment by mwbrooks** [comment]
Short but a good start. @timkim are there any URLs that we can link to help get started with each plugin?

**Comment by timkim** [comment]
I've linked to all the repos which has pretty much all the information already.

**Comment by mwbrooks** [comment]
Okay, only other feedback to use `inline code` or _italics_ for the repo names.

**Comment by timkim** [comment]
It is done.

**Pull request merged**
